// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * An IP is a single IP address, a slice of bytes.
 * Functions in this package accept either 4-byte (IPv4)
 * or 16-byte (IPv6) slices as input.
 * 
 * Note that in this documentation, referring to an
 * IP address as an IPv4 address or an IPv6 address
 * is a semantic property of the address, not just the
 * length of the byte slice: a 16-byte slice can still
 * be an IPv4 address.
 * @typedef {string} IP
 */

/**
 * IPAddr represents the address of an IP end point.
 */
export class IPAddr {
    /**
     * Creates a new IPAddr instance.
     * @param {Partial<IPAddr>} [$$source = {}] - The source object to create the IPAddr.
     */
    constructor($$source = {}) {
        if (!("IP" in $$source)) {
            /**
             * @member
             * @type {IP}
             */
            this["IP"] = "";
        }
        if (!("Zone" in $$source)) {
            /**
             * IPv6 scoped addressing zone
             * @member
             * @type {string}
             */
            this["Zone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPAddr instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IPAddr}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPAddr(/** @type {Partial<IPAddr>} */($$parsedSource));
    }
}
