// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as probing$0 from "../../../github.com/prometheus-community/pro-bing/models.js";

/**
 * @param {string} host
 * @param {number} count
 * @returns {$CancellablePromise<probing$0.Statistics | null>}
 */
export function Ping(host, count) {
    return $Call.ByID(3869394011, host, count).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = probing$0.Statistics.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
