// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as net$0 from "../../../net/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Statistics represent the stats of a currently running or finished
 * pinger operation.
 */
export class Statistics {
    /**
     * Creates a new Statistics instance.
     * @param {Partial<Statistics>} [$$source = {}] - The source object to create the Statistics.
     */
    constructor($$source = {}) {
        if (!("PacketsRecv" in $$source)) {
            /**
             * PacketsRecv is the number of packets received.
             * @member
             * @type {number}
             */
            this["PacketsRecv"] = 0;
        }
        if (!("PacketsSent" in $$source)) {
            /**
             * PacketsSent is the number of packets sent.
             * @member
             * @type {number}
             */
            this["PacketsSent"] = 0;
        }
        if (!("PacketsRecvDuplicates" in $$source)) {
            /**
             * PacketsRecvDuplicates is the number of duplicate responses there were to a sent packet.
             * @member
             * @type {number}
             */
            this["PacketsRecvDuplicates"] = 0;
        }
        if (!("PacketLoss" in $$source)) {
            /**
             * PacketLoss is the percentage of packets lost.
             * @member
             * @type {number}
             */
            this["PacketLoss"] = 0;
        }
        if (!("IPAddr" in $$source)) {
            /**
             * IPAddr is the address of the host being pinged.
             * @member
             * @type {net$0.IPAddr | null}
             */
            this["IPAddr"] = null;
        }
        if (!("Addr" in $$source)) {
            /**
             * Addr is the string address of the host being pinged.
             * @member
             * @type {string}
             */
            this["Addr"] = "";
        }
        if (!("Rtts" in $$source)) {
            /**
             * Rtts is all of the round-trip times sent via this pinger.
             * @member
             * @type {time$0.Duration[]}
             */
            this["Rtts"] = [];
        }
        if (!("TTLs" in $$source)) {
            /**
             * TTLs is all of the TTLs received via this pinger.
             * @member
             * @type {string}
             */
            this["TTLs"] = "";
        }
        if (!("MinRtt" in $$source)) {
            /**
             * MinRtt is the minimum round-trip time sent via this pinger.
             * @member
             * @type {time$0.Duration}
             */
            this["MinRtt"] = time$0.Duration.$zero;
        }
        if (!("MaxRtt" in $$source)) {
            /**
             * MaxRtt is the maximum round-trip time sent via this pinger.
             * @member
             * @type {time$0.Duration}
             */
            this["MaxRtt"] = time$0.Duration.$zero;
        }
        if (!("AvgRtt" in $$source)) {
            /**
             * AvgRtt is the average round-trip time sent via this pinger.
             * @member
             * @type {time$0.Duration}
             */
            this["AvgRtt"] = time$0.Duration.$zero;
        }
        if (!("StdDevRtt" in $$source)) {
            /**
             * StdDevRtt is the standard deviation of the round-trip times sent via
             * this pinger.
             * @member
             * @type {time$0.Duration}
             */
            this["StdDevRtt"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Statistics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Statistics}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("IPAddr" in $$parsedSource) {
            $$parsedSource["IPAddr"] = $$createField4_0($$parsedSource["IPAddr"]);
        }
        if ("Rtts" in $$parsedSource) {
            $$parsedSource["Rtts"] = $$createField6_0($$parsedSource["Rtts"]);
        }
        if ("TTLs" in $$parsedSource) {
            $$parsedSource["TTLs"] = $$createField7_0($$parsedSource["TTLs"]);
        }
        return new Statistics(/** @type {Partial<Statistics>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = net$0.IPAddr.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
